[package]
name = "rust-neighborlist"
version = "0.1.1"
authors = ["Mario Geiger <geiger.mario@gmail.com"]
edition = "2021"

[lib]
name = "neighborlist"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17", features = ["abi3-py37"] }
numpy = { version = "0.17" }

[workspace]